[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[forms]]
  name = "quote"
  success_url = "/success"

  [forms.fields]
    name = { type = "text", required = true }
    email = { type = "email", required = true }
    message = { type = "text", required = true }
    files = { type = "file" }

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"